# Generated by Django 5.0.1 on 2024-02-13 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20)),
                ('transcript', models.FileField(upload_to='transcripts/')),
                ('transcript_hash', models.CharField(max_length=64)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('certificate_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('STUDENT_NOT_FOUND', 'Student not found'), ('NOT_ORIGINAL', 'Not Original')], default='PENDING', max_length=20)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
