# Generated by Django 5.0.1 on 2024-02-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='faulty_document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
