# Generated by Django 5.0.1 on 2024-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('graduation_date', models.DateField()),
                ('enrollment_date', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('degree_certificate', models.FileField(upload_to='degree_certificates/')),
                ('transcript', models.FileField(upload_to='transcripts/')),
            ],
        ),
    ]
